/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import service.ClienteService;
import service.ProductoService;
import service.VentaService;
import model.Venta;
import model.DetalleVenta;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.Producto;

/**
 *
 * @author john2
 */
public class VentaPanel extends javax.swing.JPanel {

    private ClienteService clienteService;
    private ProductoService productoService;
    private VentaService ventaService;

    Venta ventaActual;
    
    /**
     * Creates new form VentaPanel
     */
public VentaPanel(ClienteService clienteService, ProductoService productoService, VentaService ventaService) {
    this.clienteService = clienteService;
    this.productoService = productoService;
    this.ventaService = ventaService;

    ventaActual = new Venta(1, null); 

    initComponents();
    cargarClientes();
    cargarProductos();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboClientes = new javax.swing.JComboBox<>();
        comboProductos = new javax.swing.JComboBox<>();
        txtCantidad = new javax.swing.JTextField();
        lblCantidad = new javax.swing.JLabel();
        btnAgregarProducto = new javax.swing.JButton();
        scrollDetalle = new javax.swing.JScrollPane();
        tablaDetalle = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblProducto = new javax.swing.JLabel();
        btnFinalizarVenta = new javax.swing.JButton();
        scrollVentas = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable();

        comboClientes.addActionListener(this::comboClientesActionPerformed);

        comboProductos.addActionListener(this::comboProductosActionPerformed);

        lblCantidad.setText("Cantidad:");

        btnAgregarProducto.setText("Agregar Producto");
        btnAgregarProducto.addActionListener(this::btnAgregarProductoActionPerformed);

        tablaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Precio", "Cantidad", "Subtotal"
            }
        ));
        scrollDetalle.setViewportView(tablaDetalle);

        lblTotal.setText("Total: 0 ");

        lblCliente.setText("Cliente:");

        lblProducto.setText("Producto:");

        btnFinalizarVenta.setText("Finalizar Venta");
        btnFinalizarVenta.addActionListener(this::btnFinalizarVentaActionPerformed);

        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Total"
            }
        ));
        scrollVentas.setViewportView(tablaVentas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCantidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgregarProducto)
                                .addGap(30, 30, 30)
                                .addComponent(btnFinalizarVenta))
                            .addComponent(scrollDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                            .addComponent(lblTotal)
                            .addComponent(scrollVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblProducto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente)
                    .addComponent(comboClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProducto)
                    .addComponent(comboProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidad)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarProducto)
                    .addComponent(btnFinalizarVenta))
                .addGap(26, 26, 26)
                .addComponent(scrollDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblTotal)
                .addGap(18, 18, 18)
                .addComponent(scrollVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboClientesActionPerformed

    private void comboProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboProductosActionPerformed

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        try {

    if (comboProductos.getSelectedItem() == null) {

        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Seleccione un producto"
        );

        return;
    }

    int cantidad = Integer.parseInt(txtCantidad.getText());

    if (cantidad <= 0) {

        javax.swing.JOptionPane.showMessageDialog(
            this,
            "La cantidad debe ser positiva"
        );

        return;
    }

    String nombreProducto =
        comboProductos.getSelectedItem().toString();

    Producto productoSeleccionado = null;

    for (Producto p : productoService.getListaProductos()) {

        if (p.getNombre().equals(nombreProducto)) {

            productoSeleccionado = p;
            break;
        }
    }

    if (productoSeleccionado == null) {
        return;
    }

    DetalleVenta detalle =
        new DetalleVenta(productoSeleccionado, cantidad);

    ventaActual.agregarDetalle(detalle);

    DefaultTableModel modelo =
        (DefaultTableModel) tablaDetalle.getModel();

    modelo.addRow(new Object[]{
        productoSeleccionado.getNombre(),
        productoSeleccionado.getPrecio(),
        cantidad,
        detalle.getSubtotal()
    });

    lblTotal.setText(
        "Total: " + ventaActual.calcularTotal()
    );

    txtCantidad.setText("");

} catch (NumberFormatException e) {

    javax.swing.JOptionPane.showMessageDialog(
        this,
        "La cantidad debe ser numérica"
    );
}
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void btnFinalizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarVentaActionPerformed
        String nombreCliente = comboClientes.getSelectedItem().toString();

Cliente clienteSeleccionado = null;

for (Cliente c : clienteService.obtenerClientes()) {
    if (c.getNombre().equals(nombreCliente)) {
        clienteSeleccionado = c;
        break;
    }
}

if (clienteSeleccionado == null) {
    return;
}

ventaActual.setCliente(clienteSeleccionado);

ventaService.registrarVenta(ventaActual);

DefaultTableModel modeloVentas = (DefaultTableModel) tablaVentas.getModel();

modeloVentas.addRow(new Object[]{
    ventaActual.getId(),
    ventaActual.getCliente().getNombre(),
    ventaActual.calcularTotal()
});

javax.swing.JOptionPane.showMessageDialog(this, "Venta registrada correctamente");

DefaultTableModel modelo = (DefaultTableModel) tablaDetalle.getModel();
modelo.setRowCount(0);

lblTotal.setText("Total: 0");

ventaActual = new Venta(
    ventaService.getListaVentas().size() + 1,
    null
);
    }//GEN-LAST:event_btnFinalizarVentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnFinalizarVenta;
    private javax.swing.JComboBox<String> comboClientes;
    private javax.swing.JComboBox<String> comboProductos;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JScrollPane scrollDetalle;
    private javax.swing.JScrollPane scrollVentas;
    private javax.swing.JTable tablaDetalle;
    private javax.swing.JTable tablaVentas;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables

 private void cargarClientes() {
    comboClientes.removeAllItems();
    
    for (Cliente c : clienteService.obtenerClientes()) {
        comboClientes.addItem(c.getNombre());
    }
}
    
private void cargarProductos() {
    comboProductos.removeAllItems();

    for (Producto p : productoService.getListaProductos()) {
        comboProductos.addItem(p.getNombre());
    }
}
public void recargarDatos() {
    cargarClientes();
    cargarProductos();
}
}
